package:
  name: compute_graph
  version: 1.1.2

source:
  git_tag: 1.1.2
  git_url: https://github.com/cdat/compute_graph

requirements:
  build:
    - python
    - setuptools
    - nose
    - coverage
    - pip

  run:
    - python

build:
    number: 1
    noarch: python
    script: python -m pip install --no-deps --ignore-installed

about:
  home: https://github.com/cdat/compute_graph
  license: BSD
  summary: "Library to assemble a Directed Acyclic Graph representing an abstract computation, and execute it."
