package:
  name: compute_graph
  version: 1.0

source:
  git_tag: 1.0
  git_url: https://github.com/uv-cdat/compute_graph

requirements:
  build:
    - python
    - setuptools
    - nose
    - coverage

  run:
    - python

about:
  home: https://github.com/uv-cdat/compute_graph
  license: BSD
  summary: "Library to assemble a Directed Acyclic Graph representing an abstract computation, and execute it."

build:
    noarch_python: True